name: CI

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run linting
        run: |
          check-json ./hymnals/**/*.json
          end-of-file-fixer ./hymnals/**/*.json
          pretty-format-json --no-ensure-ascii ./hymnals/**/*.json
          trailing-whitespace-fixer --markdown-linebreak-ext=md ./hymnals/**/*.json
          check-jsonschema --schemafile ./json-schema.json ./hymnals/**/*.json
